// Generated by gencpp from file service/add.msg
// DO NOT EDIT!


#ifndef SERVICE_MESSAGE_ADD_H
#define SERVICE_MESSAGE_ADD_H

#include <ros/service_traits.h>


#include <service/addRequest.h>
#include <service/addResponse.h>


namespace service
{

struct add
{

typedef addRequest Request;
typedef addResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct add
} // namespace service


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::service::add > {
  static const char* value()
  {
    return "4781436a0c2affec8025955a6041e481";
  }

  static const char* value(const ::service::add&) { return value(); }
};

template<>
struct DataType< ::service::add > {
  static const char* value()
  {
    return "service/add";
  }

  static const char* value(const ::service::add&) { return value(); }
};


// service_traits::MD5Sum< ::service::addRequest> should match
// service_traits::MD5Sum< ::service::add >
template<>
struct MD5Sum< ::service::addRequest>
{
  static const char* value()
  {
    return MD5Sum< ::service::add >::value();
  }
  static const char* value(const ::service::addRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::service::addRequest> should match
// service_traits::DataType< ::service::add >
template<>
struct DataType< ::service::addRequest>
{
  static const char* value()
  {
    return DataType< ::service::add >::value();
  }
  static const char* value(const ::service::addRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::service::addResponse> should match
// service_traits::MD5Sum< ::service::add >
template<>
struct MD5Sum< ::service::addResponse>
{
  static const char* value()
  {
    return MD5Sum< ::service::add >::value();
  }
  static const char* value(const ::service::addResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::service::addResponse> should match
// service_traits::DataType< ::service::add >
template<>
struct DataType< ::service::addResponse>
{
  static const char* value()
  {
    return DataType< ::service::add >::value();
  }
  static const char* value(const ::service::addResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SERVICE_MESSAGE_ADD_H
