// Generated by gencpp from file my_msgs/Median_gps.msg
// DO NOT EDIT!


#ifndef MY_MSGS_MESSAGE_MEDIAN_GPS_H
#define MY_MSGS_MESSAGE_MEDIAN_GPS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_msgs
{
template <class ContainerAllocator>
struct Median_gps_
{
  typedef Median_gps_<ContainerAllocator> Type;

  Median_gps_()
    : longitude(0.0)
    , latitude(0.0)  {
    }
  Median_gps_(const ContainerAllocator& _alloc)
    : longitude(0.0)
    , latitude(0.0)  {
  (void)_alloc;
    }



   typedef double _longitude_type;
  _longitude_type longitude;

   typedef double _latitude_type;
  _latitude_type latitude;





  typedef boost::shared_ptr< ::my_msgs::Median_gps_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_msgs::Median_gps_<ContainerAllocator> const> ConstPtr;

}; // struct Median_gps_

typedef ::my_msgs::Median_gps_<std::allocator<void> > Median_gps;

typedef boost::shared_ptr< ::my_msgs::Median_gps > Median_gpsPtr;
typedef boost::shared_ptr< ::my_msgs::Median_gps const> Median_gpsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_msgs::Median_gps_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_msgs::Median_gps_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_msgs::Median_gps_<ContainerAllocator1> & lhs, const ::my_msgs::Median_gps_<ContainerAllocator2> & rhs)
{
  return lhs.longitude == rhs.longitude &&
    lhs.latitude == rhs.latitude;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_msgs::Median_gps_<ContainerAllocator1> & lhs, const ::my_msgs::Median_gps_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::my_msgs::Median_gps_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_msgs::Median_gps_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_msgs::Median_gps_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_msgs::Median_gps_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_msgs::Median_gps_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_msgs::Median_gps_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_msgs::Median_gps_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fd6c3d0b911e124b1f0b5a2ade9c1a01";
  }

  static const char* value(const ::my_msgs::Median_gps_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfd6c3d0b911e124bULL;
  static const uint64_t static_value2 = 0x1f0b5a2ade9c1a01ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_msgs::Median_gps_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_msgs/Median_gps";
  }

  static const char* value(const ::my_msgs::Median_gps_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_msgs::Median_gps_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# 发送中位数靶标的gps坐标\n"
"float64 longitude\n"
"float64 latitude\n"
;
  }

  static const char* value(const ::my_msgs::Median_gps_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_msgs::Median_gps_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.longitude);
      stream.next(m.latitude);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Median_gps_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_msgs::Median_gps_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_msgs::Median_gps_<ContainerAllocator>& v)
  {
    s << indent << "longitude: ";
    Printer<double>::stream(s, indent + "  ", v.longitude);
    s << indent << "latitude: ";
    Printer<double>::stream(s, indent + "  ", v.latitude);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_MSGS_MESSAGE_MEDIAN_GPS_H
