// Generated by gencpp from file my_msgs/Signal.msg
// DO NOT EDIT!


#ifndef MY_MSGS_MESSAGE_SIGNAL_H
#define MY_MSGS_MESSAGE_SIGNAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace my_msgs
{
template <class ContainerAllocator>
struct Signal_
{
  typedef Signal_<ContainerAllocator> Type;

  Signal_()
    : header()
    , signal(0)  {
    }
  Signal_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , signal(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _signal_type;
  _signal_type signal;





  typedef boost::shared_ptr< ::my_msgs::Signal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_msgs::Signal_<ContainerAllocator> const> ConstPtr;

}; // struct Signal_

typedef ::my_msgs::Signal_<std::allocator<void> > Signal;

typedef boost::shared_ptr< ::my_msgs::Signal > SignalPtr;
typedef boost::shared_ptr< ::my_msgs::Signal const> SignalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_msgs::Signal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_msgs::Signal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_msgs::Signal_<ContainerAllocator1> & lhs, const ::my_msgs::Signal_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.signal == rhs.signal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_msgs::Signal_<ContainerAllocator1> & lhs, const ::my_msgs::Signal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::my_msgs::Signal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_msgs::Signal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_msgs::Signal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_msgs::Signal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_msgs::Signal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_msgs::Signal_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_msgs::Signal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "78f41e618127bce049dd6104d9c31dc5";
  }

  static const char* value(const ::my_msgs::Signal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x78f41e618127bce0ULL;
  static const uint64_t static_value2 = 0x49dd6104d9c31dc5ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_msgs::Signal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_msgs/Signal";
  }

  static const char* value(const ::my_msgs::Signal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_msgs::Signal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# 消息作用：发送状态信号，表示飞机目前是处于侦查状态还是已经结束侦查航线（结束侦查后程序就要开始处理数据了）\n"
"\n"
"# header：利用header.stamp为消息打上时间戳，方便使用ApproximateTimeSynchronizer同步消息。\n"
"# signal: 状态信号，0表示仍然处于侦查状态，1表示已经结束侦查\n"
"\n"
"\n"
"Header header\n"
"int32 signal\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::my_msgs::Signal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_msgs::Signal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.signal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Signal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_msgs::Signal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_msgs::Signal_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "signal: ";
    Printer<int32_t>::stream(s, indent + "  ", v.signal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_MSGS_MESSAGE_SIGNAL_H
